/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package csc_teacher_helper

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
    }
}
